CREATE DATABASE ENCUESTA;

USE ENCUESTA;
GO
CREATE TABLE TIPO (
	ID_TIPO INT IDENTITY(1,1) PRIMARY KEY,
	DESCRIPCION NCHAR(20)
)
GO
CREATE TABLE ENCUESTA (
	ID_ENCUESTA INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE NCHAR(20) NOT NULL,
	EDAD INT NOT NULL,
	CARRO CHAR NOT NULL,
	TIPO INT,
	MARCA NCHAR(20),
	MODELO NCHAR(20),
	COMPRA CHAR,
	FECHA DATETIME NOT NULL,
	FOREIGN KEY (TIPO) REFERENCES TIPO(ID_TIPO)
)
GO
INSERT INTO TIPO
(DESCRIPCION)
VALUES
('SEDAN'),
('4X4'),
('COUPE')
GO
INSERT INTO ENCUESTA
(NOMBRE, EDAD, CARRO, TIPO, MARCA, MODELO, FECHA)
VALUES
('LUIS',20,'S',1,'TOYOTA','COROLLA','2018-02-28')
GO
INSERT INTO ENCUESTA
(NOMBRE, EDAD, CARRO, TIPO, MARCA, MODELO, FECHA,COMPRA)
VALUES
('CARLOS',24,'N',2,'NISSAN','KICKS',GETDATE(),'S')
GO
INSERT INTO ENCUESTA
(NOMBRE, EDAD,CARRO,FECHA,COMPRA)
VALUES
('ROSA',22,'N',GETDATE(),'N')

GO
CREATE PROCEDURE REPORTE_CANTIDAD_REGISTROS
AS
BEGIN
	SELECT COUNT(1) 'CANTIDAD' FROM ENCUESTA
END
GO
exec REPORTE_CANTIDAD_REGISTROS
GO
CREATE PROCEDURE COMPRA_NO_CARRO
AS
BEGIN
	SELECT COUNT(1) 'CANTIDAD' FROM ENCUESTA 
	WHERE COMPRA = 'N'
END
GO
CREATE PROCEDURE VEHICULOS_MARCA
AS
BEGIN
	SELECT MARCA, COUNT(1) 'CANTIDAD' 
	FROM ENCUESTA
	WHERE MARCA IS NOT NULL
	GROUP BY MARCA
END
GO
CREATE PROCEDURE REPORTE_FILTRO
@VALOR CHAR
AS
BEGIN
	SELECT * FROM ENCUESTA WHERE COMPRA = @VALOR
END

GO 
EXEC REPORTE_FILTRO 'N'